# restart sshd
- name: restart sshd
  service:
    name: sshd
    state: restarted

# enable and start fail2ban
- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

# enable and start rsyslog
- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

# enable and start sssd
- name: enable sssd
  service:
    name: sssd
    state: started
