# Disable SSH root login
- name: base_files | disable root SSH login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PermitRootLogin'
    line: "PermitRootLogin no"
    owner: root
    group: root
    mode: '0600'
  #notify: restart sshd
  
# Allow X11
- name: base_files | allow X11 forwarding
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#11Forwarding no'
    line: "11Forwarding yes"
    owner: root
    group: root
    mode: '0600'
  #notify: restart sshd

# Add reference to my logging server in /etc/rsyslog.conf
# This will just add the line to the end of the file if the line isn't already there
- name: base_files | send logs to the logging VM
  lineinfile:
    path: /etc/rsyslog.conf
    line: "*.* @logging.pengels.local:20514;RSYSLOG_SyslogProtocol23Format"
  notify: restart rsyslog

# copy the admins sudoers file to the system
- name: base_files | copy my admin sudoers file to the system
  copy:
    src: files/admins.sudoers
    dest: /etc/sudoers.d/admins
    mode: '0440'
    owner: root
    group: root

#- name: restart sshd
#  service:
#    name: sshd
#    state: restarted

# enable and start fail2ban
- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
    enabled: yes

# enable and start rsyslog
- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
    enabled: yes

# enable and start sssd
#- name: enable sssd
#  service:
#    name: sssd
#    state: restarted
#    enabled: yes
