# This task copies files to the remote system

- name: files | copy k8s.conf to /etc/sysctl.d/
  copy:
    src: files/sysctl.d-k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: 0644
  notify: apply sysctl changes

- name: files | copy k8s.conf to /etc/modules-load.d/
  copy:
    src: files/modules-load.d-k8s.conf
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: 0644
  notify: apply sysctl changes

- name: files | copy kubernetes.repo to /etc/yum.repos.d/
  copy:
    src: files/kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: 0644
  register: result1

- name: files | copy docker-ce.repo to /etc/yum.repos.d/
  copy:
    src: files/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: 0644
  register: result2

- name: files | renew the dnf cache
  dnf:
    update_cache: yes
  when: result1 is succeeded or result2 is succeeded

- name: files | Import Docker and Kubernetes keys
  rpm_key:
    state: present
    key: "{{ item }}"
  loop: "{{ gpg_keys }}"

## Only run these when copying the file made a change
#- handlers:
#
#  - name: apply sysctl changes
#    command: sysctl --system
#
