# This task installs the required packages for kubernetes to function
#- name: packages | install required packages
#  yum:
#    name: " {{ packages }} "
#    state: present
#  notify: enable kubelet
#
- name: packages | install required packages the dumb way because for some reason the right way doesn't work
  command:
    cmd: "yum install kubelet kubectl kubeadm docker -y"
