# Example: Restart myservice
#
#- name: restart myservice
#  service:
#    name: myservice
#    state: restarted
#
#- handlers:
#  - name: apply sysctl changes
#    command: sudo sysctl --system
#
#  - name: enable kubelet
#    service:
#      name: kubelet
#      state: started
#      enabled: yes
